
// ============================================
// RESTORED EXPORTS
// ============================================

export const travelCategories = [\n[16] 1188:   { id: 'nature', name: 'Nature', icon: '🌿', gradient: 'from-green-400 to-emerald-600', description: 'Immerse in natural wonders' },\n[17] 1189:   { id: 'mountains', name: 'Mountains', icon: '🏔️', gradient: 'from-slate-400 to-slate-700', description: 'Conquer majestic peaks' },\n[18] 1190:   { id: 'beaches', name: 'Beaches', icon: '🏖️', gradient: 'from-cyan-400 to-blue-500', description: 'Paradise shores await' },\n[19] 1191:   { id: 'deserts', name: 'Deserts', icon: '🏜️', gradient: 'from-amber-400 to-orange-600', description: 'Golden sand adventures' },\n[20] 1192:   { id: 'historical', name: 'Historical', icon: '🏛️', gradient: 'from-amber-300 to-yellow-600', description: 'Walk through time' },\n[21] 1193:   { id: 'cities', name: 'Cities', icon: '🌆', gradient: 'from-purple-400 to-indigo-600', description: 'Urban exploration' },\n[22] 1194:   { id: 'skyscrapers', nam\n<truncated 646 bytes>\nname: 'Swedish Krona', symbol: 'kr', rate: 10.82 },\n[30] 1262: ];

export const features = [') && \\n      line.includes('export const featuredTestimonials = [') && \\n      line.includes('export const scrollingTestimonials = [')) {\\n    \\n    console.log(`Found complete candidate block! Line length: ${line.length}`);\\n    matchText = line;\\n    // Don't break, let's get the latest one!\\n  }\\n}\\n\\nif (matchText) {\\n  fs.writeFileSync('scratch/found_match_raw.txt', matchText);\\n  console.log(\\\"Saved raw match to scratch/found_match_raw.txt\\\");\\n  \\n  // Let's do some regex extraction of the variables!\\n  const getArray = (varName) => {\\n    const pattern = new RegExp(`export const ${varName} = \\\\\\\\s*\\\\\\\\[([\\\\\\\\s\\\\\\\\S]*?)\\\\\\\\];

export const featuredTestimonials = [') && \\n      line.includes('export const scrollingTestimonials = [')) {\\n    \\n    console.log(`Found complete candidate block! Line length: ${line.length}`);\\n    matchText = line;\\n    // Don't break, let's get the latest one!\\n  }\\n}\\n\\nif (matchText) {\\n  fs.writeFileSync('scratch/found_match_raw.txt', matchText);\\n  console.log(\\\"Saved raw match to scratch/found_match_raw.txt\\\");\\n  \\n  // Let's do some regex extraction of the variables!\\n  const getArray = (varName) => {\\n    const pattern = new RegExp(`export const ${varName} = \\\\\\\\s*\\\\\\\\[([\\\\\\\\s\\\\\\\\S]*?)\\\\\\\\];

export const scrollingTestimonials = [')) {\\n    \\n    console.log(`Found complete candidate block! Line length: ${line.length}`);\\n    matchText = line;\\n    // Don't break, let's get the latest one!\\n  }\\n}\\n\\nif (matchText) {\\n  fs.writeFileSync('scratch/found_match_raw.txt', matchText);\\n  console.log(\\\"Saved raw match to scratch/found_match_raw.txt\\\");\\n  \\n  // Let's do some regex extraction of the variables!\\n  const getArray = (varName) => {\\n    const pattern = new RegExp(`export const ${varName} = \\\\\\\\s*\\\\\\\\[([\\\\\\\\s\\\\\\\\S]*?)\\\\\\\\];
